-- Evolve the existing grading history. Run after the existing skill_scores schema.
CREATE TABLE IF NOT EXISTS public.grading_config_versions (
    grading_version text PRIMARY KEY,
    taxonomy_version text NOT NULL,
    configuration jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Some existing installations imported skill_scores.id as a plain bigint.
-- Establish an insert default only when one is absent; preserve existing IDs.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema='public' AND table_name='skill_scores'
                 AND column_name='id' AND is_identity='NO' AND column_default IS NULL) THEN
        ALTER TABLE public.skill_scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        PERFORM setval(pg_get_serial_sequence('public.skill_scores','id'),
                      GREATEST(COALESCE((SELECT MAX(id) FROM public.skill_scores), 0), 1),
                      EXISTS(SELECT 1 FROM public.skill_scores));
    END IF;
END $$;

ALTER TABLE public.skill_scores
    ADD COLUMN IF NOT EXISTS job_key text,
    ADD COLUMN IF NOT EXISTS grading_version text REFERENCES public.grading_config_versions(grading_version),
    ADD COLUMN IF NOT EXISTS taxonomy_version text,
    ADD COLUMN IF NOT EXISTS role_lane text,
    ADD COLUMN IF NOT EXISTS lane_scores jsonb,
    ADD COLUMN IF NOT EXISTS fit_score numeric CHECK (fit_score BETWEEN 0 AND 100),
    ADD COLUMN IF NOT EXISTS learning_score numeric CHECK (learning_score BETWEEN 0 AND 100),
    ADD COLUMN IF NOT EXISTS pre_ai_score numeric CHECK (pre_ai_score BETWEEN 0 AND 100),
    ADD COLUMN IF NOT EXISTS confidence numeric CHECK (confidence BETWEEN 0 AND 1),
    ADD COLUMN IF NOT EXISTS ai_review_required boolean,
    ADD COLUMN IF NOT EXISTS deterministic_grade jsonb;

CREATE INDEX IF NOT EXISTS skill_scores_job_key_version_idx
    ON public.skill_scores(job_key, grading_version, created_at DESC);

CREATE OR REPLACE VIEW public.job_grade_history AS
SELECT id AS job_grade_id, job_key, job_id, grading_version, taxonomy_version,
       role_lane, lane_scores, fit_score, learning_score, pre_ai_score, confidence,
       ai_review_required, deterministic_grade->'reason_codes' AS reason_codes,
       deterministic_grade->'triggered_rules' AS triggered_rules,
       deterministic_grade, created_at AS graded_at
FROM public.skill_scores
WHERE grading_version IS NOT NULL;

COMMENT ON COLUMN public.skill_scores.confidence IS
    'Explainable deterministic heuristic; not a statistically calibrated probability.';
COMMENT ON TABLE public.grading_config_versions IS
    'Immutable authoring/configuration and implementation-hash snapshots; YAML remains the authoring source.';
COMMENT ON VIEW public.job_grade_history IS
    'Versioned deterministic grades in the existing skill_scores history; no job descriptions duplicated.';
